import Image from 'next/image'
import Link from 'next/link'
import type { Venture } from '@/lib/ventures'
import Nav from '@/components/Nav'
import Footer from '@/components/Footer'

function ConsultationButton({ venture, light = false }: { venture: Venture; light?: boolean }) {
  return <a href={`mailto:hello@ladyprowess.com?subject=Consultation%20about%20${encodeURIComponent(venture.name)}`} className={`inline-flex min-h-12 items-center justify-center rounded-full px-7 py-3.5 text-sm font-bold transition ${light ? 'bg-white text-primary hover:bg-blue-50' : 'bg-primary text-white hover:bg-primary-dim'}`}>Book a consultation</a>
}

export default function VentureDetail({ venture }: { venture: Venture }) {
  return (
    <main className="min-h-screen bg-bg text-parchment">
      <Nav />

      <section className="relative overflow-hidden border-b border-ink-border bg-white px-6 pb-20 pt-36 sm:px-8 md:px-20 md:pb-24 md:pt-44">
        <div aria-hidden className="absolute right-[-7rem] top-20 h-[28rem] w-[28rem] rounded-full bg-blue-100/70 blur-3xl" />
        <div className="relative mx-auto grid max-w-[1280px] gap-12 lg:grid-cols-[1.12fr_0.88fr] lg:items-center lg:gap-20">
          <div>
            <Link href="/support" className="text-xs font-semibold text-muted hover:text-primary">← All ventures</Link>
            <p className="mt-8 font-head text-[0.64rem] font-bold uppercase tracking-[0.18em] text-primary">{venture.eyebrow}</p>
            <h1 className="mt-4 font-display text-[clamp(2.5rem,5vw,4.5rem)] font-extrabold leading-none">{venture.name}</h1>
            <p className="mt-6 max-w-2xl text-[1.02rem] leading-[1.85] text-muted md:text-[1.1rem]">{venture.introduction}</p>
            <div className="mt-8 flex flex-col gap-3 sm:flex-row"><ConsultationButton venture={venture} /><a href={venture.website} target="_blank" rel="noopener noreferrer" className="inline-flex min-h-12 items-center justify-center rounded-full border border-ink-border bg-white px-7 py-3.5 text-sm font-bold hover:border-primary/40">Visit the website ↗</a></div>
          </div>
          <aside className="rounded-[2rem] border border-ink-border bg-bg p-5 shadow-[0_24px_70px_rgba(18,18,18,0.08)] md:p-8"><div className="flex min-h-[220px] items-center justify-center rounded-[1.4rem] bg-white p-10"><div className="relative h-28 w-full max-w-[300px]"><Image src={venture.logo} alt={venture.name} fill priority className="object-contain" sizes="300px" /></div></div><div className="mt-6"><span className="inline-flex rounded-full bg-blue-50 px-3 py-1.5 text-xs font-semibold text-primary">{venture.status}</span><p className="mt-4 text-[0.92rem] leading-7 text-muted">{venture.summary}</p></div></aside>
        </div>
      </section>

      <section className="border-b border-ink-border px-6 py-14 sm:px-8 md:px-20"><div className="mx-auto grid max-w-[1180px] grid-cols-2 gap-px overflow-hidden rounded-2xl border border-ink-border bg-ink-border md:grid-cols-4">{venture.stats.map(stat => <div key={stat.label} className="bg-white p-5 md:p-7"><p className="font-display text-2xl font-extrabold text-primary md:text-3xl">{stat.value}</p><p className="mt-2 text-xs leading-5 text-muted">{stat.label}</p></div>)}</div></section>

      <section className="border-b border-ink-border bg-white px-6 py-20 sm:px-8 md:px-20 md:py-28"><div className="mx-auto grid max-w-[1180px] gap-10 lg:grid-cols-[0.72fr_1.28fr] lg:gap-20"><div><p className="font-head text-[0.64rem] font-bold uppercase tracking-[0.18em] text-primary">Why I built it</p><h2 className="mt-4 font-display text-3xl font-extrabold leading-tight md:text-4xl">The story behind {venture.name}.</h2></div><div className="space-y-5 text-[1rem] leading-[1.9] text-muted">{venture.story.map(paragraph => <p key={paragraph}>{paragraph}</p>)}</div></div></section>

      <section className="border-b border-ink-border px-6 py-20 sm:px-8 md:px-20 md:py-24"><div className="mx-auto max-w-[1180px]"><div className="grid gap-4 md:grid-cols-2"><div className="rounded-3xl bg-parchment p-7 text-white md:p-9"><span className="font-head text-[0.62rem] font-bold uppercase tracking-[0.16em] text-blue-300">The problem</span><p className="mt-5 text-[1rem] leading-8 text-gray-300">{venture.problem}</p></div><div className="rounded-3xl bg-primary p-7 text-white md:p-9"><span className="font-head text-[0.62rem] font-bold uppercase tracking-[0.16em] text-blue-100">The answer</span><p className="mt-5 text-[1rem] leading-8 text-blue-50">{venture.solution}</p></div></div></div></section>

      <section className="border-b border-ink-border bg-white px-6 py-20 sm:px-8 md:px-20 md:py-28"><div className="mx-auto max-w-[1180px]"><div className="mb-12 grid gap-5 md:grid-cols-2 md:items-end"><div><p className="font-head text-[0.64rem] font-bold uppercase tracking-[0.18em] text-primary">What it offers</p><h2 className="mt-4 font-display text-3xl font-extrabold md:text-4xl">How the product works.</h2></div><p className="max-w-lg text-[0.94rem] leading-7 text-muted md:justify-self-end">The product is designed around clear, practical actions for the people it serves.</p></div><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{venture.features.map((feature, index) => <article key={feature.title} className="rounded-2xl border border-ink-border bg-bg p-6"><span className="font-head text-[0.6rem] font-bold text-primary">{String(index + 1).padStart(2, '0')}</span><h3 className="mt-4 font-display text-lg font-extrabold">{feature.title}</h3><p className="mt-3 text-[0.85rem] leading-6 text-muted">{feature.body}</p></article>)}</div></div></section>

      <section className="border-b border-ink-border px-6 py-20 sm:px-8 md:px-20 md:py-24"><div className="mx-auto grid max-w-[1180px] gap-5 lg:grid-cols-3"><div className="rounded-3xl border border-ink-border bg-white p-7"><p className="font-head text-[0.62rem] font-bold uppercase tracking-[0.16em] text-primary">Who it serves</p><ul className="mt-5 space-y-3">{venture.audience.map(item => <li key={item} className="flex gap-3 text-sm leading-6"><span className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-primary" />{item}</li>)}</ul></div><div className="rounded-3xl border border-ink-border bg-white p-7"><p className="font-head text-[0.62rem] font-bold uppercase tracking-[0.16em] text-primary">How it earns</p><ul className="mt-5 space-y-3">{venture.model.map(item => <li key={item} className="flex gap-3 text-sm leading-6"><span className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-primary" />{item}</li>)}</ul></div><div className="rounded-3xl border border-ink-border bg-white p-7"><p className="font-head text-[0.62rem] font-bold uppercase tracking-[0.16em] text-primary">Current priorities</p><ul className="mt-5 space-y-3">{venture.priorities.map(item => <li key={item} className="flex gap-3 text-sm leading-6"><span className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-primary" />{item}</li>)}</ul></div></div></section>

      {venture.videos && <section className="border-b border-ink-border bg-white px-6 py-20 sm:px-8 md:px-20 md:py-28"><div className="mx-auto max-w-[1180px]"><p className="font-head text-[0.64rem] font-bold uppercase tracking-[0.18em] text-primary">Product recordings</p><h2 className="mt-4 font-display text-3xl font-extrabold md:text-4xl">See {venture.name} in use.</h2><p className="mt-4 max-w-xl text-[0.94rem] leading-7 text-muted">These short recordings show real product flows instead of asking you to imagine how the platform works.</p><div className="mt-10 grid gap-5 md:grid-cols-3">{venture.videos.map(video => <article key={video.title} className="rounded-2xl border border-ink-border bg-bg p-3"><div className="h-[520px] overflow-hidden rounded-xl bg-surface-2"><iframe className="h-full w-full" src={video.src} title={video.title} allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowFullScreen /></div><p className="px-2 pb-2 pt-4 text-sm font-bold">{video.title}</p></article>)}</div></div></section>}

      {venture.raise && <section className="border-b border-ink-border bg-parchment px-6 py-20 text-white sm:px-8 md:px-20 md:py-28"><div className="mx-auto max-w-[1180px]"><div className="grid gap-10 lg:grid-cols-[0.7fr_1.3fr] lg:items-end"><div><p className="font-head text-[0.64rem] font-bold uppercase tracking-[0.18em] text-blue-300">The current raise</p><p className="mt-4 font-display text-5xl font-extrabold md:text-7xl">{venture.raise.amount}</p><p className="mt-4 text-sm text-gray-400">Funding for the next stage of product and market growth</p></div><div className="grid grid-cols-2 gap-px overflow-hidden rounded-2xl bg-gray-700">{venture.raise.details.map(detail => <div key={detail.label} className="bg-[#181818] p-5"><p className="font-display text-xl font-extrabold">{detail.value}</p><p className="mt-2 text-xs text-gray-400">{detail.label}</p></div>)}</div></div><div className="mt-12 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{venture.raise.allocation.map(item => <div key={item.label} className="rounded-2xl border border-gray-700 p-5"><p className="font-display text-2xl font-extrabold text-blue-300">{item.percent}</p><p className="mt-2 text-sm text-gray-300">{item.label}</p></div>)}</div></div></section>}

      <section className="bg-primary px-6 py-20 text-white sm:px-8 md:px-20 md:py-24"><div className="mx-auto grid max-w-[1180px] gap-10 lg:grid-cols-[1fr_0.8fr] lg:items-center"><div><p className="font-head text-[0.64rem] font-bold uppercase tracking-[0.18em] text-blue-100">Support {venture.name}</p><h2 className="mt-4 max-w-2xl font-display text-3xl font-extrabold leading-tight md:text-4xl">Start with a real conversation about the business.</h2><p className="mt-5 max-w-2xl text-[0.94rem] leading-7 text-blue-100">You can ask questions, discuss support, explore a partnership, or book time to understand the product more deeply.</p></div><div className="rounded-3xl bg-white/10 p-6"><p className="text-sm font-bold">Useful forms of support</p><ul className="mt-4 space-y-2 text-sm text-blue-100">{venture.support.map(item => <li key={item}>• {item}</li>)}</ul><div className="mt-6 flex flex-col gap-3 sm:flex-row">{venture.paymentUrl && <a href={venture.paymentUrl} target="_blank" rel="noopener noreferrer" className="inline-flex min-h-12 items-center justify-center rounded-full bg-white px-7 py-3.5 text-sm font-bold text-primary transition hover:bg-blue-50">Support with crypto</a>}<ConsultationButton venture={venture} light /></div></div></div></section>

      <section className="bg-white px-6 py-14 text-center sm:px-8 md:px-20"><p className="text-xs leading-6 text-muted">Information on this page is provided for general discussion. It is not investment advice or a public offer.</p></section>
      <Footer />
    </main>
  )
}
